name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install Dependencies
        run: |
          for i in {1..3}; do
            echo "Attempt $i to install dependencies..."
            if npm ci --prefer-offline --no-audit; then
              echo "Dependencies installed successfully!"
              break
            else
              echo "Attempt $i failed. Waiting 10 seconds before retry..."
              sleep 10
            fi
          done
          if [ $? -ne 0 ]; then
            echo "All attempts failed. Exiting with error."
            exit 1
          fi
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4